name: Deploy WWW

on:
  push:
    branches:
      - main
    paths:
      - "www/**"

jobs:
  deploy_www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEPLOY }}"
          projectId: handong-newsletter
          channelId: live
          entryPoint: www
